// Use edition 2023 until protoc-gen-go supports edition 2024.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: claims.proto

package claims

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IDClaims are the claims that will be included in the ID token.
type IDClaims struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Subject           *string                `protobuf:"bytes,1,opt,name=subject,json=sub"`
	xxx_hidden_Email             *string                `protobuf:"bytes,2,opt,name=email"`
	xxx_hidden_EmailVerified     bool                   `protobuf:"varint,3,opt,name=email_verified"`
	xxx_hidden_Picture           *string                `protobuf:"bytes,4,opt,name=picture"`
	xxx_hidden_Name              *string                `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Groups            []string               `protobuf:"bytes,6,rep,name=groups"`
	xxx_hidden_PreferredUsername *string                `protobuf:"bytes,7,opt,name=preferred_username"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *IDClaims) Reset() {
	*x = IDClaims{}
	mi := &file_claims_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDClaims) ProtoMessage() {}

func (x *IDClaims) ProtoReflect() protoreflect.Message {
	mi := &file_claims_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IDClaims) GetSubject() string {
	if x != nil {
		if x.xxx_hidden_Subject != nil {
			return *x.xxx_hidden_Subject
		}
		return ""
	}
	return ""
}

func (x *IDClaims) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *IDClaims) GetEmailVerified() bool {
	if x != nil {
		return x.xxx_hidden_EmailVerified
	}
	return false
}

func (x *IDClaims) GetPicture() string {
	if x != nil {
		if x.xxx_hidden_Picture != nil {
			return *x.xxx_hidden_Picture
		}
		return ""
	}
	return ""
}

func (x *IDClaims) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *IDClaims) GetGroups() []string {
	if x != nil {
		return x.xxx_hidden_Groups
	}
	return nil
}

func (x *IDClaims) GetPreferredUsername() string {
	if x != nil {
		if x.xxx_hidden_PreferredUsername != nil {
			return *x.xxx_hidden_PreferredUsername
		}
		return ""
	}
	return ""
}

func (x *IDClaims) SetSubject(v string) {
	x.xxx_hidden_Subject = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *IDClaims) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *IDClaims) SetEmailVerified(v bool) {
	x.xxx_hidden_EmailVerified = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *IDClaims) SetPicture(v string) {
	x.xxx_hidden_Picture = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *IDClaims) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *IDClaims) SetGroups(v []string) {
	x.xxx_hidden_Groups = v
}

func (x *IDClaims) SetPreferredUsername(v string) {
	x.xxx_hidden_PreferredUsername = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *IDClaims) HasSubject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *IDClaims) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *IDClaims) HasEmailVerified() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *IDClaims) HasPicture() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *IDClaims) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *IDClaims) HasPreferredUsername() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *IDClaims) ClearSubject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Subject = nil
}

func (x *IDClaims) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Email = nil
}

func (x *IDClaims) ClearEmailVerified() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_EmailVerified = false
}

func (x *IDClaims) ClearPicture() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Picture = nil
}

func (x *IDClaims) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Name = nil
}

func (x *IDClaims) ClearPreferredUsername() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_PreferredUsername = nil
}

type IDClaims_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Subject           *string
	Email             *string
	EmailVerified     *bool
	Picture           *string
	Name              *string
	Groups            []string
	PreferredUsername *string
}

func (b0 IDClaims_builder) Build() *IDClaims {
	m0 := &IDClaims{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Subject != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Subject = b.Subject
	}
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Email = b.Email
	}
	if b.EmailVerified != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_EmailVerified = *b.EmailVerified
	}
	if b.Picture != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Picture = b.Picture
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_Groups = b.Groups
	if b.PreferredUsername != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_PreferredUsername = b.PreferredUsername
	}
	return m0
}

var File_claims_proto protoreflect.FileDescriptor

const file_claims_proto_rawDesc = "" +
	"\n" +
	"\fclaims.proto\x12\x0epassidp.claims\x1a!google/protobuf/go_features.proto\"\xd4\x01\n" +
	"\bIDClaims\x12\x14\n" +
	"\asubject\x18\x01 \x01(\tR\x03sub\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12&\n" +
	"\x0eemail_verified\x18\x03 \x01(\bR\x0eemail_verified\x12\x18\n" +
	"\apicture\x18\x04 \x01(\tR\apicture\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06groups\x18\x06 \x03(\tR\x06groups\x12.\n" +
	"\x12preferred_username\x18\a \x01(\tR\x12preferred_usernameB\x1fZ\x15lds.li/passidp/claims\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_claims_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_claims_proto_goTypes = []any{
	(*IDClaims)(nil), // 0: passidp.claims.IDClaims
}
var file_claims_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_claims_proto_init() }
func file_claims_proto_init() {
	if File_claims_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_claims_proto_rawDesc), len(file_claims_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_claims_proto_goTypes,
		DependencyIndexes: file_claims_proto_depIdxs,
		MessageInfos:      file_claims_proto_msgTypes,
	}.Build()
	File_claims_proto = out.File
	file_claims_proto_goTypes = nil
	file_claims_proto_depIdxs = nil
}
