// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: groups.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const getUserActiveGroupMembershipsForMigration = `-- name: GetUserActiveGroupMembershipsForMigration :many
SELECT ug.id, ug.user_id, ug.group_id, ug.start_date, ug.end_date, ug.created_at, g.name as group_name, g.description as group_description
FROM user_groups ug
JOIN groups g ON ug.group_id = g.id
WHERE ug.user_id = ?
  AND g.active = TRUE
  AND (ug.end_date IS NULL OR ug.end_date > CURRENT_TIMESTAMP)
ORDER BY g.name
`

type GetUserActiveGroupMembershipsForMigrationRow struct {
	ID               string
	UserID           string
	GroupID          string
	StartDate        time.Time
	EndDate          sql.NullTime
	CreatedAt        time.Time
	GroupName        string
	GroupDescription sql.NullString
}

func (q *Queries) GetUserActiveGroupMembershipsForMigration(ctx context.Context, userID string) ([]GetUserActiveGroupMembershipsForMigrationRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserActiveGroupMembershipsForMigration, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserActiveGroupMembershipsForMigrationRow
	for rows.Next() {
		var i GetUserActiveGroupMembershipsForMigrationRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.GroupName,
			&i.GroupDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
