// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package queries

import (
	"context"
)

const getCredentialsForMigration = `-- name: GetCredentialsForMigration :many


SELECT id, credential_id, user_id, name, credential_data, created_at FROM credentials
`

// -- name: GetUserCredentials :many
// SELECT * FROM credentials c
// WHERE user_id = ?;
// -- name: UpdateCredentialDataByCredentialID :exec
// UPDATE credentials SET credential_data = ? WHERE credential_id = ?;
func (q *Queries) GetCredentialsForMigration(ctx context.Context) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, getCredentialsForMigration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.CredentialID,
			&i.UserID,
			&i.Name,
			&i.CredentialData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersForMigration = `-- name: GetUsersForMigration :many

SELECT id, email, full_name, enrollment_key, override_subject, webauthn_handle FROM users
`

// -- name: CreateUserCredential :exec
// INSERT INTO credentials (id, user_id, name, credential_id, credential_data, created_at)
// VALUES (?, ?, ?, ?, ?, ?);
func (q *Queries) GetUsersForMigration(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersForMigration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.EnrollmentKey,
			&i.OverrideSubject,
			&i.WebauthnHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
