// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserCredential = `-- name: CreateUserCredential :exec
INSERT INTO credentials (id, user_id, name, credential_id, credential_data, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUserCredentialParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Name           string
	CredentialID   []byte
	CredentialData []byte
	CreatedAt      time.Time
}

func (q *Queries) CreateUserCredential(ctx context.Context, arg CreateUserCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createUserCredential,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.CredentialID,
		arg.CredentialData,
		arg.CreatedAt,
	)
	return err
}

const getUserCredentials = `-- name: GetUserCredentials :many
SELECT id, credential_id, user_id, name, credential_data, created_at FROM credentials c
WHERE user_id = ?
`

func (q *Queries) GetUserCredentials(ctx context.Context, userID uuid.UUID) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, getUserCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.CredentialID,
			&i.UserID,
			&i.Name,
			&i.CredentialData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersForMigration = `-- name: GetUsersForMigration :many
SELECT id, email, full_name, enrollment_key, override_subject, webauthn_handle FROM users
`

func (q *Queries) GetUsersForMigration(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersForMigration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.EnrollmentKey,
			&i.OverrideSubject,
			&i.WebauthnHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredentialDataByCredentialID = `-- name: UpdateCredentialDataByCredentialID :exec
UPDATE credentials SET credential_data = ? WHERE credential_id = ?
`

func (q *Queries) UpdateCredentialDataByCredentialID(ctx context.Context, credentialData []byte, credentialID []byte) error {
	_, err := q.db.ExecContext(ctx, updateCredentialDataByCredentialID, credentialData, credentialID)
	return err
}
